// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServicesStore.Api.Author.Persistence;

namespace ServicesStore.Api.Author.Migrations
{
    [DbContext(typeof(ContextAuthor))]
    partial class ContextAuthorModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ServicesStore.Api.Author.Model.AcademicGrade", b =>
                {
                    b.Property<int>("IdAcademicGrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AcademicCenter")
                        .HasColumnType("text");

                    b.Property<string>("AcademicGradeGuid")
                        .HasColumnType("text");

                    b.Property<string>("AcademicGradeName")
                        .HasColumnType("text");

                    b.Property<int?>("AuthorBookIdAuthorBook")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdAuthorBook")
                        .HasColumnType("integer");

                    b.HasKey("IdAcademicGrade");

                    b.HasIndex("AuthorBookIdAuthorBook");

                    b.ToTable("AcademicGrades");
                });

            modelBuilder.Entity("ServicesStore.Api.Author.Model.AuthorBook", b =>
                {
                    b.Property<int>("IdAuthorBook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("AuthorBirthdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AuthorBookGuid")
                        .HasColumnType("text");

                    b.Property<string>("AuthorLastName")
                        .HasColumnType("text");

                    b.Property<string>("AuthorName")
                        .HasColumnType("text");

                    b.HasKey("IdAuthorBook");

                    b.ToTable("AuthorBooks");
                });

            modelBuilder.Entity("ServicesStore.Api.Author.Model.AcademicGrade", b =>
                {
                    b.HasOne("ServicesStore.Api.Author.Model.AuthorBook", "AuthorBook")
                        .WithMany("AcademicGradeList")
                        .HasForeignKey("AuthorBookIdAuthorBook");
                });
#pragma warning restore 612, 618
        }
    }
}
