// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServicesStore.Api.ShopingCart.Persistence;

namespace ServicesStore.Api.ShopingCart.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ServicesStore.Api.ShopingCart.Model.ShoppingCartDetail", b =>
                {
                    b.Property<int>("ShoppingCartDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("SelectedProduct")
                        .HasColumnType("text");

                    b.Property<int>("ShopingCartSessionId")
                        .HasColumnType("int");

                    b.Property<int?>("ShoppingCartSessionShopingCartSessionId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartDetailId");

                    b.HasIndex("ShoppingCartSessionShopingCartSessionId");

                    b.ToTable("ShoppingCartDetails");
                });

            modelBuilder.Entity("ServicesStore.Api.ShopingCart.Model.ShoppingCartSession", b =>
                {
                    b.Property<int>("ShopingCartSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime");

                    b.HasKey("ShopingCartSessionId");

                    b.ToTable("ShoppingCartSessions");
                });

            modelBuilder.Entity("ServicesStore.Api.ShopingCart.Model.ShoppingCartDetail", b =>
                {
                    b.HasOne("ServicesStore.Api.ShopingCart.Model.ShoppingCartSession", "ShoppingCartSession")
                        .WithMany("ShoppingCartDetail")
                        .HasForeignKey("ShoppingCartSessionShopingCartSessionId");
                });
#pragma warning restore 612, 618
        }
    }
}
